// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package postgres

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.createTodoStmt, err = db.PrepareContext(ctx, createTodo); err != nil {
		return nil, fmt.Errorf("error preparing query CreateTodo: %w", err)
	}
	if q.deleteTodobyIdStmt, err = db.PrepareContext(ctx, deleteTodobyId); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteTodobyId: %w", err)
	}
	if q.gettodoStmt, err = db.PrepareContext(ctx, gettodo); err != nil {
		return nil, fmt.Errorf("error preparing query Gettodo: %w", err)
	}
	if q.gettodosinggleStmt, err = db.PrepareContext(ctx, gettodosinggle); err != nil {
		return nil, fmt.Errorf("error preparing query Gettodosinggle: %w", err)
	}
	if q.updateTodoStmt, err = db.PrepareContext(ctx, updateTodo); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateTodo: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.createTodoStmt != nil {
		if cerr := q.createTodoStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createTodoStmt: %w", cerr)
		}
	}
	if q.deleteTodobyIdStmt != nil {
		if cerr := q.deleteTodobyIdStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteTodobyIdStmt: %w", cerr)
		}
	}
	if q.gettodoStmt != nil {
		if cerr := q.gettodoStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing gettodoStmt: %w", cerr)
		}
	}
	if q.gettodosinggleStmt != nil {
		if cerr := q.gettodosinggleStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing gettodosinggleStmt: %w", cerr)
		}
	}
	if q.updateTodoStmt != nil {
		if cerr := q.updateTodoStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateTodoStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                 DBTX
	tx                 *sql.Tx
	createTodoStmt     *sql.Stmt
	deleteTodobyIdStmt *sql.Stmt
	gettodoStmt        *sql.Stmt
	gettodosinggleStmt *sql.Stmt
	updateTodoStmt     *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                 tx,
		tx:                 tx,
		createTodoStmt:     q.createTodoStmt,
		deleteTodobyIdStmt: q.deleteTodobyIdStmt,
		gettodoStmt:        q.gettodoStmt,
		gettodosinggleStmt: q.gettodosinggleStmt,
		updateTodoStmt:     q.updateTodoStmt,
	}
}
